Repository rancher/turtles-docs, pull requests merged in 2024-10, with the labels that each got.

#163 extend docs on clusterclass
  docs/getting-started/cluster-class/intro.md
  docs/getting-started/cluster-class/provision.md
  docs/reference-guides/providers/certified.md
Labels: area/documentation, kind/enhancement

#167 add missing variable to aks cluster class guide
  docs/getting-started/cluster-class/provision.md
Labels: area/documentation

#170 add label on new version pr
  .github/workflows/version-publish.yaml
Labels: kind/enhancement

#171 Update dev and architecture sections
  docs/developer-guide/development.md
  docs/developer-guide/intro.md
  docs/reference-guides/architecture/30000ft_view.png
  docs/reference-guides/architecture/components.md
Labels: area/documentation
