Repository rancher/turtles-docs, pull requests merged in 2025-05, with the labels that each got.

#297 Add vSphere Kubeadm documentation
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/enhancement, area/clusterclass

#296 Add RKE2+EC2 docs
  .gitignore
  docs/next/modules/en/pages/user/clusterclass.adoc
  docs/next/modules/en/pages/user/clusters.adoc
  docs/v0.19/modules/en/pages/user/clusters.adoc
Labels: area/documentation

#301 add reference to docker/rke2 config map example
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/cleanup

#303 add new demo video using cluster class and fleet
  docs/next/modules/en/pages/index.adoc
Labels: area/documentation, kind/enhancement

#304 Actualize AWS ClusterClass documentation
  docs/next/modules/en/pages/user/clusterclass.adoc
  docs/v0.19/modules/en/pages/user/clusterclass.adoc
Labels: kind/cleanup, area/clusterclass

#308 CAPV+RKE2 and registration SL Micro against SCC
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/enhancement
