Repository rancher/turtles-docs, pull requests merged in 2025-03, with the labels that each got.

#236 Updatecli revert releasepost version bump
  .github/workflows/updatecli.yaml
Labels: kind/bug, area/ci

#246 Review and update documentation
  docs/next/modules/en/pages/developer/development.adoc
  docs/next/modules/en/pages/operator/airgapped.adoc
  docs/next/modules/en/pages/operator/certification.adoc
  docs/next/modules/en/pages/operator/certificationsuite.adoc
  docs/next/modules/en/pages/operator/chart.adoc
  docs/next/modules/en/pages/operator/clusterclass.adoc
  docs/next/modules/en/pages/reference/certified.adoc
  docs/next/modules/en/pages/tutorials/first-cluster.adoc
  docs/next/modules/en/pages/user/caapf.adoc
  docs/next/modules/en/pages/user/clusters.adoc
  docs/next/modules/en/pages/user/fleet.adoc
  docs/v0.17/modules/en/pages/developer/development.adoc
  docs/v0.17/modules/en/pages/operator/airgapped.adoc
  docs/v0.17/modules/en/pages/operator/certification.adoc
  docs/v0.17/modules/en/pages/operator/certificationsuite.adoc
  docs/v0.17/modules/en/pages/operator/chart.adoc
  docs/v0.17/modules/en/pages/operator/clusterclass.adoc
  docs/v0.17/modules/en/pages/reference/certified.adoc
  docs/v0.17/modules/en/pages/tutorials/first-cluster.adoc
  docs/v0.17/modules/en/pages/user/caapf.adoc
  docs/v0.17/modules/en/pages/user/clusterclass.adoc
  docs/v0.17/modules/en/pages/user/clusters.adoc
Labels: area/documentation, kind/enhancement

#248 Fix rendering issue with tab usage
  docs/next/modules/en/pages/tutorials/first-cluster.adoc
Labels: kind/bug, area/documentation

#245 Fix issue with generatig Docker RKE2 example
  docs/next/modules/en/pages/user/clusters.adoc
Labels: area/documentation, kind/enhancement

#242 Add section about how to use quickstart script
  docs/next/modules/en/pages/tutorials/first-cluster.adoc
  docs/next/modules/en/pages/tutorials/quickstart.adoc
Labels: area/documentation, kind/enhancement

#256 fix: broken link after re-structuring caprke2 templates
  docs/next/modules/en/pages/user/clusters.adoc
  docs/v0.17/modules/en/pages/user/clusters.adoc
Labels: kind/bug, area/documentation

#257 Omit default namespace
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation

#258 docs: self-managed azure clusters are now supported
  docs/next/modules/en/pages/reference/certified.adoc
Labels: area/documentation, kind/cleanup

#259 Fix typu in CLUSTER_CLASS_NAME variable
  docs/next/modules/en/pages/user/clusters.adoc
Labels: area/documentation

#253 Fix namaspace for Azure AKS example
  docs/next/modules/en/pages/user/clusters.adoc
  package-lock.json
Labels: area/documentation

#263 Bump `releasepost` policy to align with latest action version
  .github/workflows/updatecli.yaml
  updatecli-compose.yaml
Labels: kind/bug, area/ci, kind/cleanup

#262 Add AKS ClusterClass example
  docs/next/modules/en/pages/user/clusterclass.adoc
  docs/next/modules/en/pages/user/clusters.adoc
Labels: area/documentation

#260 Adding troubleshooting section for Rancher Turtles
  docs/next/modules/en/images/lineage-cluster-output.png
  docs/next/modules/en/nav.adoc
  docs/next/modules/en/pages/index.adoc
  docs/next/modules/en/pages/troubleshooting/troubleshooting.adoc
  package-lock.json
Labels: area/documentation

#265 Use CAAPF and HelmApps for Azure Class example
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation

#247 Prepare next version of docs for v0.18 release
  docs/next/modules/en/pages/operator/certificationsuite.adoc
  docs/next/modules/en/pages/tutorials/first-cluster.adoc
  docs/next/modules/en/pages/tutorials/quickstart.adoc
  docs/next/modules/en/pages/user/clusters.adoc
  docs/v0.17/modules/en/pages/user/clusters.adoc
Labels: area/documentation, area/release
