Repository rancher/turtles-docs, pull requests merged in 2025-04, with the labels that each got.

#274 Fix typo and broken link
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/cleanup

#276 Fix envsubst command for first cluster tutorial
  docs/next/modules/en/pages/tutorials/first-cluster.adoc
  docs/next/modules/en/pages/user/clusterclass.adoc
  docs/next/modules/en/pages/user/clusters.adoc
Labels: kind/bug, area/documentation

#277 Install Calico CNI with HelmApp
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: kind/enhancement, area/clusterclass

#278 Fix rendering
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/cleanup

#280 Remove misleading comment, prevent installing many CNIs
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/cleanup

#275 Add vSphere ClusterClass example to documentation
  docs/next/modules/en/pages/user/clusterclass.adoc
  docs/next/modules/en/pages/user/clusters.adoc
Labels: kind/enhancement, area/clusterclass

#283 Fix rendering typo
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: kind/bug, area/documentation

#281 docs: add capa+cabpk class example
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/enhancement

#285 Revert "Add vSphere ClusterClass example to documentation"
  docs/next/modules/en/pages/user/clusterclass.adoc
  docs/next/modules/en/pages/user/clusters.adoc
Labels: area/documentation, kind/cleanup, area/clusterclass

#287 Add vSphere RKE2 Class documentation
  .gitignore
  Makefile
  docs/next/modules/en/pages/user/clusterclass.adoc
  docs/v0.18/modules/en/pages/user/clusterclass.adoc
  docs/v0.19/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/enhancement
