Repository rancher/turtles-docs, pull requests merged in 2025-06, with the labels that each got.

#313 Add Azure Kubeadm ClusterClass example
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/enhancement

#315 Add/improve resources reference documentation
  docs/next/modules/en/nav.adoc
  docs/next/modules/en/pages/index.adoc
  docs/next/modules/en/pages/operator/certification.adoc
  docs/next/modules/en/pages/operator/certificationsuite.adoc
  docs/next/modules/en/pages/operator/clusterclass.adoc
  docs/next/modules/en/pages/operator/manual.adoc
  docs/next/modules/en/pages/overview/architecture.adoc
  docs/next/modules/en/pages/overview/certified.adoc
  docs/next/modules/en/pages/overview/features.adoc
  docs/next/modules/en/pages/overview/glossary.adoc
  docs/next/modules/en/pages/overview/intro.adoc
  docs/next/modules/en/pages/reference/capiprovider.adoc
  docs/next/modules/en/pages/reference/clusterctlconfig.adoc
  docs/next/modules/en/pages/tutorials/first-cluster.adoc
  docs/next/modules/en/pages/user/clusters.adoc
Labels: area/documentation, kind/enhancement

#317 Bump Turtles version everywhere on new release
  .github/workflows/pre-release.yaml
  .github/workflows/publish-version.yaml
  README.adoc
  docs/next/modules/en/pages/user/clusters.adoc
  docs/v0.13/modules/en/pages/reference-guides/providers/howto.adoc
  docs/v0.14/modules/en/pages/reference-guides/providers/howto.adoc
  docs/v0.15/modules/en/pages/reference-guides/providers/howto.adoc
  docs/v0.16/modules/en/pages/reference-guides/providers/howto.adoc
  docs/v0.17/modules/en/pages/operator/certificationsuite.adoc
  docs/v0.17/modules/en/pages/user/clusters.adoc
  docs/v0.18/modules/en/pages/user/clusterclass.adoc
  docs/v0.18/modules/en/pages/user/clusters.adoc
  docs/v0.19/modules/en/pages/user/clusterclass.adoc
  docs/v0.19/modules/en/pages/user/clusters.adoc
  docs/v0.20/modules/en/pages/operator/certificationsuite.adoc
  docs/v0.20/modules/en/pages/user/clusterclass.adoc
  docs/v0.20/modules/en/pages/user/clusters.adoc
  replace-rules.json
  tools/setexampleversion/main.go
  tools/verifybrokenlinks/main.go
Labels: kind/enhancement, area/build-and-release

#320 Use AWSClusterStaticIdentity in examples
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/enhancement, area/clusterclass

#324 fix: broken link to capz docs
  docs/next/modules/en/pages/user/clusterclass.adoc
  docs/v0.18/modules/en/pages/user/clusterclass.adoc
  docs/v0.19/modules/en/pages/user/clusterclass.adoc
  docs/v0.20/modules/en/pages/user/clusterclass.adoc
Labels: kind/bug, area/documentation

#327 add gcp kubeadm clusterclass example
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/enhancement

#328 update ccm naming for aws and gcp
  docs/next/modules/en/pages/user/clusterclass.adoc
Labels: area/documentation, kind/enhancement
