Repository rancher/turtles-docs, pull requests merged in 2025-01, with the labels that each got.

#193 Clarify recommended way of disabling Rancher features
  docs/next/modules/en/pages/getting-started/install-rancher-turtles/using_helm.adoc
  docs/next/modules/en/pages/getting-started/install-rancher-turtles/using_rancher_dashboard.adoc
  docs/v0.15/modules/en/pages/getting-started/install-rancher-turtles/using_helm.adoc
  docs/v0.15/modules/en/pages/getting-started/install-rancher-turtles/using_rancher_dashboard.adoc
Labels: kind/enhancement

#195 fix: add empty changelogs index file
  docs/next/modules/en/nav.adoc
  docs/next/modules/en/pages/changelogs/index.adoc
Labels: kind/bug, area/documentation

#200 chore: bump updatecli policy for release notes
  updatecli-compose.yaml
Labels: kind/bug, area/ci

#199 docs: update helm chart values
  docs/next/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
Labels: area/documentation

#205 feat: filter rc releases for changelog generator
  .releasepost.yaml
  docs/next/modules/en/pages/changelogs/changelogs/v0.15.0-rc1.adoc
  docs/next/modules/en/pages/changelogs/index.adoc
Labels: area/documentation, kind/enhancement

#210 📖 Update dependency versions in the next/v0.16 version of the docs
  docs/next/modules/en/pages/developer-guide/install_capi_operator.adoc
  docs/next/modules/en/pages/getting-started/install-rancher-turtles/using_helm.adoc
  docs/next/modules/en/pages/index.adoc
  docs/next/modules/en/pages/tasks/capi-operator/installing_core_provider.adoc
  docs/v0.16/modules/en/pages/developer-guide/install_capi_operator.adoc
  docs/v0.16/modules/en/pages/getting-started/install-rancher-turtles/using_helm.adoc
  docs/v0.16/modules/en/pages/index.adoc
  docs/v0.16/modules/en/pages/tasks/capi-operator/installing_core_provider.adoc
Labels: area/documentation
